setup.py: remove the 'U' open mode removed in Python 3.11
The 'U' open mode was removed in Python 3.11. See:
https://docs.python.org/3.11/library/functions.html#open

Installing with Python 3.11 fails with:

    /path/to/python-magic-wormhole-mailbox-server-0.4.1/setup.py", line 20, in <module>
        long_description=open('README.md', 'rU').read(),
                         ^^^^^^^^^^^^^^^^^^^^^^^
    ValueError: invalid mode: 'rU'

This patch removes the 'U' open mode.

Signed-off-by: Julien Olivain <ju.o@free.fr>